prometheus/client_rust

derive-text-encode/src/lib.rs
derive-text-encode/tests/lib.rs

Field names like `r#type` are problematic as `r#` is not a valid
OpenMetrics label name but one needs to use keyword identifier syntax
(aka. raw identifiers) as `type` is a keyword.
Makes sure `r#type` is replaced by `type` in the OpenMetrics output.

derive-text-encode: Handle keyword identifiers aka raw identifiers

---

CHANGELOG.md
Cargo.toml
README.md
src/encoding/text.rs
src/metrics.rs
src/metrics/info.rs

Open Metrics `Info` metric "to expose textual information which SHOULD
NOT change during process lifetime".
```
use open_metrics_client::metrics::info::Info;
let _info = Info::new(vec![("os", "GNU/linux")]);
```

src/metrics: Implement info metrics

---

CHANGELOG.md
Cargo.toml
src/encoding/text.rs
src/registry.rs

Allow creating a sub-registry namespaced by a label instead of a metric
name prefix.

src/registry: Add sub_registry_with_label

---

CHANGELOG.md
Cargo.toml

Re-releases `v0.12.1` as `v0.13.0`. See https://github.com/mxinden/rust-open-metrics-client/pull/24 for details.
I am unable to come up with a fix to the type inference issue, thus releasing as `v0.13.0` instead.
//CC @divagant-martian

*: Prepare v0.13.0

---

CHANGELOG.md
Cargo.toml
README.md
benches/encoding/text.rs
benches/family.rs
derive-text-encode/Cargo.toml
derive-text-encode/src/lib.rs
derive-text-encode/tests/lib.rs
examples/tide.rs
src/encoding/text.rs
src/lib.rs
src/metrics/counter.rs
src/metrics/exemplar.rs
src/metrics/family.rs
src/metrics/gauge.rs
src/metrics/histogram.rs
src/metrics/info.rs
src/registry.rs

- Move repository from
https://github.com/mxinden/rust-open-metrics-client to
https://github.com/prometheus/client_rust.
- Rename crate from `open-metrics-client` to `prometheus-client`.
- Rename import paths from `open_metrics_client` to `prometheus_client`.
See https://groups.google.com/g/prometheus-developers/c/E67ByGmVQKM for
details.
Signed-off-by: Max Inden <mail@max-inden.de>

*: Rename to prometheus-client

---

CHANGELOG.md
Cargo.toml
examples/custom-metric.rs
src/encoding/text.rs

By exposing the various `Encoder` builder methods, downstream users can
implement their custom metrics using `EncodeMetric`.
See https://github.com/prometheus/client_rust/issues/36 for additional context.
//CC @phyber

src/encoding/text.rs: Expose Encoder methods

---

.github/workflows/rust.yml
CHANGELOG.md
src/metrics/counter.rs
src/metrics/exemplar.rs
src/metrics/gauge.rs

As stated in #37 in regard to how this crate handles `std::sync::atomic::AtomicU64`, this PR removes any occurrences of this struct and instead defaults to its 32-bit version where appropriate.
```
[lychee  client_rust | drop-atomic64-for-unsupported-platforms  $] cross build --release --target=mipsel-unknown-linux-gnu
Finished release [optimized] target(s) in 0.09s
```

*: Remove AtomicU64 on unsupported platforms

---

src/encoding/text.rs

Raised due to latest clippy update.

src/encoding: Remove unnecessary flatten

---

examples/tide.rs

There is no need for mutable access to the `Registry` once all metrics
have been registered. Encoding the registered metrics does not require a
mutable reference.
With that in mind, an `Arc` is good enough. There is no need for a
`Mutex`.
Signed-off-by: Max Inden <mail@max-inden.de>

examples/tide: Remove unnecessary Mutex

---

CHANGELOG.md
Cargo.toml
src/encoding/text.rs
src/registry.rs

This will allow the default `Registry` to be used in multi-threaded
environments (e.g. web servers) where the registry needs to be shared
between threads.
Closes #57.

Replace `SendEncodeMetric` with `SendSyncEncodeMetric`

---

src/metrics/histogram.rs

As suggested and discussed in https://github.com/prometheus/client_rust/issues/61,
this commit adds a comment that describes unavailability of default
values for buckets.
I thought about providing test case that demonstrates using iterator for buckets as arguments. But thought that would be a bit overkill. If you think it would help let me know.

src/metrics/histogram.rs Document no default buckets

---

CHANGELOG.md
src/registry.rs

They interact with builtin implementation in confusing ways:
https://github.com/rust-lang/rust/issues/77143
Fixes https://github.com/prometheus/client_rust/issues/68

src/registry.rs: Remove Add trait impls

---

CHANGELOG.md
src/registry.rs

Adds the ability to create a registry with a prefix.
This is actually already possible through the below hack but this makes it a lot easier and neater.
```rust
let prefixed_registry = {
let mut registry = <Registry>::default();
let prefixed_registry = registry.sub_registry_with_prefix(prefix);
std::mem::take(prefixed_registry)
};
```
This is useful to set an application-wide prefix on the single registry for all your metrics.

Add with_prefix to Registry

---

CHANGELOG.md
Cargo.toml
examples/actix-web.rs

Add actix-web example

---

CHANGELOG.md
Cargo.toml
src/encoding/text.rs
src/metrics/exemplar.rs
src/metrics/family.rs
src/metrics/histogram.rs

Before `proemtheus-client` would use the `owning_ref` crate to map the target
of a `std::sync::RwLockReadGuard`. `owning_ref` has multiple unsoundness
issues, see https://rustsec.org/advisories/RUSTSEC-2022-0040.html. Instead of
replacing `owning_ref` with a similar crate, we switch to locking via
`parking_lot` which supports the above mapping natively.
Fixes https://github.com/prometheus/client_rust/issues/77

*: Move to `parking_lot` and thus make `owning_ref` obsolete

---

src/encoding/text.rs
src/lib.rs
src/metrics.rs
src/metrics/counter.rs
src/metrics/exemplar.rs
src/metrics/family.rs
src/metrics/gauge.rs
src/metrics/histogram.rs
src/metrics/info.rs
src/registry.rs

Enforces documentation comments on every public type.

src/lib: Add `#![deny(missing_docs)]`

---

README.md

Protobuf support was added in ffc2ab6.
Thanks to the work from @ackintosh in https://github.com/prometheus/client_rust/pull/83.

README.md: Remove mention of missing Protobuf

---

CHANGELOG.md
src/metrics/family.rs

This PR adds `Family::remove` as discussed a little in #36 along with a basic test for the behaviour. We also add a `Family::clear` method as discussed in this PR.
The `Family::remove` method returns a `bool` to indicate if a label set was removed, which matches what the Go client does when removing its equivalent of a label set.
The `Family::clear` method does not return anything and always successfully clears the label sets.

src/metrics/family.rs: Add remove and clear methods, and tests

---

derive-encode/src/lib.rs
derive-encode/tests/lib.rs

`multiple applicable items in scope` error happens when there is an `encode` implementation (e.g. [`prost::Message`](https://docs.rs/prost/latest/prost/trait.Message.html)) in the same scope.
```shell
// error[E0034]: multiple applicable items in scope
//     |
// 120 |         #[derive(Clone, Hash, PartialEq, Eq, Encode)]
//     |                                              ^^^^^^ multiple `encode` found
```

derive-encode: Fix `multiple applicable items in scope` error

---

CHANGELOG.md
src/metrics/exemplar.rs

Fixes #95, i.e. that on master, you cannot create a Histogram or Counter which has both a Family and Exemplars. Also adds an example showing how to make such a histogram/counter. This example won't compile without my fix, so it also serves as a regression test :)
Running my example gives the expected output:
```
latency_sum{result="success"} 0.001345422
latency_count{result="success"} 1
latency_bucket{result="success",le="1.0"} 1 # {trace_id="3a2f90c9f80b894f"} 0.001345422
```
If you approve this PR, would you please also consider cutting a release 0.19 for it? I think most real-world exemplars will also want to use families, so I think this feature is worth releasing soon. My team at Cloudflare is gonna use my fork with this PR for now, but I'd like to start using this crate in more …

impl TypedMetric for Counter/HistogramWithExemplars

---

Cargo.toml
examples/hyper.rs

Say your Rust app is not a web server. You probably don't need to pull in a whole web framework like Axum or Actix-web just to serve one little OpenMetrics endpoint. You can just use Hyper instead. Here's an example of how to do that.
I also added this an example target in Cargo.toml, so that you can run it with cargo:
```sh
$ cargo run --example hyper  &
$ curl localhost:8001
tokio_hyper_example_example_counter_total 6
```

Example metrics server using Hyper

---

.github/workflows/rust.yml
Cargo.toml

I noticed the Dependabot PRs (#89 #90 #92), but you really have to update all three Prost crates simultaneously because otherwise you'll get weird errors between versions. So, here's one PR to bump prost's family of crates.

chore: Bump Prost to 0.11

---

CHANGELOG.md
Cargo.toml
src/metrics/family.rs

Releases https://github.com/prometheus/client_rust/pull/102 as `prometheus-client` `v0.18.1`.
Note that this targets the `release-v0.18` branch and not `master`. Port to `master` is happening in a follow up.
//CC @nox

*: Prepare v0.18.1

---

CHANGELOG.md
src/metrics/family.rs

Follow up to https://github.com/prometheus/client_rust/pull/103. See also https://github.com/prometheus/client_rust/pull/102.

Merge `release-v0.18` back into `master`

---

CHANGELOG.md
Cargo.toml
benches/encoding/proto.rs
benches/encoding/text.rs
derive-encode/Cargo.toml
derive-encode/src/lib.rs
derive-encode/tests/lib.rs
examples/actix-web.rs
examples/custom-metric.rs
examples/hyper.rs
examples/tide.rs
src/encoding.rs
src/encoding/protobuf.rs
src/encoding/text.rs
src/lib.rs
src/metrics.rs
src/metrics/counter.rs
src/metrics/exemplar.rs
src/metrics/family.rs
src/metrics/gauge.rs
src/metrics/histogram.rs
src/metrics/info.rs
src/registry.rs

Adopt encoding style similar to serde. `EncodeXXX` for a type that can be
encoded (see serde's `Serialize`) and `XXXEncoder` for a supported encoding i.e.
text and protobuf (see serde's `Serializer`).
- Compatible with Rust's additive features. Enabling the `protobuf` feature does
not change type signatures.
- `EncodeMetric` is trait object safe, and thus `Registry` can use dynamic dispatch.
- Implement a single encoding trait `EncodeMetric` per metric type instead of
one implementation per metric AND per encoding format.
- Leverage `std::fmt::Write` instead of `std::io::Write`. The OpenMetrics text
format has to be unicode compliant. The OpenMetrics Protobuf format requires
labels to be valid strings.
Builds on top of https://github.com/prometheus/client_rust/pull/100.
Status: It …

encoding/: Adopt serde style encoding

---

examples/custom-metric.rs
src/encoding.rs
src/encoding/protobuf.rs
src/encoding/text.rs
src/metrics/counter.rs
src/metrics/exemplar.rs
src/metrics/gauge.rs

No need to take ownership of the value. Relevant when using with non-copy types.
Signed-off-by: Max Inden <mail@max-inden.de>

src/encoding: Take reference for value

---

CHANGELOG.md
Cargo.toml
derive-encode/Cargo.toml
derive-encode/src/lib.rs
derive-encode/tests/lib.rs

Fixes https://github.com/prometheus/client_rust/issues/117
This introduces a new attribute to the derive code for to flatten. This matches https://serde.rs/attr-flatten.html.
This seems to work, but I have some concern that if there are duplicate fields we end up encoding all of them which may make things go awry. Checking this is hard since we would need to lookup the type, which I am not sure how to do...

feat(derive): Introduce flatten attribute

---

CHANGELOG.md
src/encoding/protobuf.rs

Fixes https://github.com/prometheus/client_rust/issues/124

protobuf: Fix label encoding

---

CHANGELOG.md
Cargo.toml
src/metrics/family.rs

Addresses feedback raised by @thomaseizinger in https://github.com/prometheus/client_rust/pull/82/files#r1158205762.
@thomaseizinger this is what we discussed in Brussels. What do you think?

refactor(family): introduce `ConstFamily` type

---

src/registry.rs

- Added `sub_registry_with_labels` method per discussion in https://github.com/prometheus/client_rust/issues/144
- Updated the tests (which should be refactored or better documented I think, it's a bit hard to figure out the hierarchy or registries)

feat(registry): add `sub_registry_with_labels`

---

CHANGELOG.md
Cargo.toml
src/registry.rs

Added new constructor per discussion in https://github.com/prometheus/client_rust/issues/146.

feat(registry): add `with_prefix_and_labels` constructor

---

CHANGELOG.md
Cargo.toml
src/collector.rs
src/encoding.rs
src/encoding/protobuf.rs
src/encoding/text.rs
src/lib.rs
src/metrics/family.rs
src/registry.rs

Let's face it, the `Collector` trait I designed in https://github.com/prometheus/client_rust/pull/82 is too complex.
Instead of having `Registry` provide access to its inner `Metric`s, have
`Registry` encode the `Metric`s directly via `Registry::encode`. In the same
vain, have `Collector::encode` encode the collected `Metric`s directly.
This allows for a much simpler `Collector` trait, removing all complexity due to
providing access to a `Metric` externally.
``` rust
/// The [`Collector`] abstraction allows users to provide additional metrics and
/// their description on each scrape.
///
/// An example use-case is an exporter that retrieves a set of operating system metrics
/// ad-hoc on each scrape.
///
/// Register a [`Collector`] with a [`Registry`](crate::registry::Registry) via
/// …
```

refactor(collector): have Registry:encode do the encoding 

---

derive-encode/LICENSE-APACHE
derive-encode/LICENSE-MIT

I am packaging the prometheus-client and prometheus-client-derive-encode crates for Fedora Linux. I noticed that the latter crate does not contain license files as it is published to crates.io.
However, both the terms of the MIT and Apache-2.0 licenses require that any (re)distributed sources contain a copy of the original license text. This is potentially problematic for the crates as published on crates.io, but definitely problematic for packaging them on Linux distributions.
This PR includes symbolic links to both license files in the derive-encode directory, which should result in "cargo package" / "cargo publish" including a copy of the license files when publishing to crates.io. This is assuming that the publishing workflow is run on an operating system that supports symbolic links …

chore(derive): include license files

---

CHANGELOG.md
Cargo.toml
src/encoding.rs

Adds blanket implementations to encode reference-counted keys and values.

feat(encoding): implement `EncodeLabelKey` and `EncodeLabelValue` for `Arc`

---

CHANGELOG.md
Cargo.toml
src/encoding.rs
src/encoding/protobuf.rs
src/encoding/text.rs
src/metrics/gauge.rs

support `Gauge<u32, AtomicU32>` metric

feat(metrics): support `Gauge<u32, AtomicU32>` type

---

Cargo.toml
examples/hyper.rs

This PR ports the hyper example to hyper 1.x.
All kudos goes to @junkurihara (https://github.com/prometheus/client_rust/pull/184).
Closes the erroneous https://github.com/prometheus/client_rust/pull/187.

chore(examples/hyper):  Port to hyper 1.x

---

CHANGELOG.md
Cargo.toml
src/encoding/text.rs

**Note: All credits for the PR, from the initial idea, implementation, and testing, belong to @amunra who is the original author of this PR and #154.**
From the original PR description:
Adds new `encode_registry` and `encode_eof` functions to allow encoding of parts of the response.
This is useful when there are multiple registries at play, or when composing metrics for a process that embeds Rust as part of its logic whilst serving metrics to Prometheus outside of Rust.
Fixes: #153
Refs: #154, #204
Thank you @amunra! 😸

feat(encoding): add functions for individually encoding registry & EOF

---

Cargo.toml
src/encoding.rs
src/lib.rs

- have docs.rs generate  with `protobuf` feature
- flag that only enabled with `protobuf` feature

docs: enable for protobuf feature

---

CHANGELOG.md
Cargo.toml
src/encoding/text.rs

Replaces https://github.com/prometheus/client_rust/pull/198.
Close #181 
Close #182 
Close #183
Close #187

chore(deps): update prost dependencies to v0.12

---

CHANGELOG.md
src/collector.rs
src/encoding.rs
src/encoding/text.rs
src/registry.rs

With these changes, I no longer get the error:
> trait `EncodeCounterValue` is not implemented for `u32`
when compiling to mips.
I have also added additional trait implementations for the other types. The reason to cast from 32 to 64 bit values is that in the end, it is casted to 64 bit values anyway, because these are the types that must be used: https://github.com/prometheus/client_rust/blob/master/src/encoding/proto/openmetrics_data_model.proto. This way, there is no need to implement `encoder.encode_u32` ... methods.
I believe this is not catched by the tests, because the library itself compiles fine to mips, until you start implementing it. Unfortunately the cross-compile check does not run the tests. I did a quick test changing the `cargo check ...` to `cargo check --target=${{ …

feat(encoding): add impls for `Encode*Value`

---

src/encoding/text.rs

This adds tests for the new capabilities enabled by #173.

Add missing tests for some 32-bit types that already work in metrics

---

CHANGELOG.md
derive-encode/tests/lib.rs
src/encoding.rs

I'm writing a label struct like this:
```
#[derive(Debug, Clone, Hash, Eq, PartialEq, EncodeLabelSet)]
struct ErrorLabels {
op: &'static str,
scheme: &'static str,
err: &'static str,
root: Arc<String>,
namespace: Arc<String>,
}
```
in this struct, the `root` and `namespace` field is nearly immutable after a client get established. i hope to use `Arc` to reduce copy Strings on updating metrics. 
but i got this error:
```
the trait bound `for<'a> &'a std::string::String: EncodeLabelValue` is not satisfied
the trait `EncodeLabelValue` is implemented for `std::string::String`
required for `Arc<std::string::String>` to implement `EncodeLabelValue`
```
it tells that we need implement &String to EncodeLabelValue.
this PR addes a implement about EncodeLabelValue for `&String`, and it can make the …

feat: allow Arc<String> on EncodeLabelSet

---

CHANGELOG.md
examples/custom-metric.rs
src/encoding.rs
src/encoding/text.rs
src/metrics/counter.rs
src/metrics/histogram.rs

Replaces https://github.com/prometheus/client_rust/pull/175.

fix(encoding): correctly handle empty family labels

---

CHANGELOG.md
src/encoding.rs
src/encoding/protobuf.rs
src/metrics/gauge.rs

Between forcing end users to do endless `as i64` for things that are clearly `u64` and having one error case for rarely used protobuf when a gauge is set to `u64::MAX`, the latter seems like the right choice.

Implement Atomic<u64> for AtomicU64 for gauges

---

CONTRIBUTING.md

the test suite in this repository has some implicit dependencies upon `protoc` and the Python client library.
in order to help newcomers get situated and effectively contributing to this project, a `CONTRIBUTING.md` file is added to help provide some guidance on how to install the protocol buffer compiler, and how to create and activate a virtual environment with the Python library installed.

chore: 💜 add `CONTRIBUTING.md` instructions

---

CHANGELOG.md
src/encoding.rs

- impl `EncodeLabelValue` for `bool`
- adjust order of some impls (just for better consistency and readability)

feat(encoding): impl `EncodeLabelValue` for `bool`

---

CHANGELOG.md
src/metrics/family.rs

Address comments in https://github.com/prometheus/client_rust/pull/230#issuecomment-2440804265

feat(metrics/family): add `get` method to Family

---

src/encoding/protobuf.rs
src/encoding/text.rs

Related to https://github.com/prometheus/OpenMetrics/issues/287
The OM 2.0 effort is kicked off, and will start developing on main. This updates the links to OpenMetrics to reference the 1.0 release. The OM project has also been moved into the prometheus github org.

update links to openmetrics to reference the v1.0.0 release

---

CHANGELOG.md
Cargo.toml
src/metrics/histogram.rs

this is a very small, **non-breaking**, alteration to the signature of `Histogram`'s constructor.
rather than accepting an `impl Iterator`, this commit changes the parameter of `Histogram::new()` to be an `impl IntoIterator` instead. this does not affect the existing contract because of the blanket `impl<I: Iterator> IntoIterator for I` implementation provided by the standard library.
by accepting `IntoIterator` however, callers providing a collection such as a `[f64; 5]` array or a `Vec<f64>` vector do not need to invoke `into_iter()` themselves at the call-site.
```rust
// now, constructing a histogram needn't involve `into_iter()`...
use prometheus_client::metrics::histogram::Histogram;
let histogram = Histogram::new([10.0, 100.0, 1_000.0]);
```
this leans on the same sugar used by …

refactor(metrics/histogram): 🎂 constructor accepts `IntoIterator`

---

CHANGELOG.md
Cargo.toml
derive-encode/Cargo.toml
derive-encode/src/lib.rs
src/encoding.rs
src/encoding/protobuf.rs
src/encoding/text.rs

this commit alters the signature of the `EncodeLabelSet::encode()` trait method, such that it now accepts a mutable reference to its encoder.
this is related to #135, and is a second proposal following previous work in #240.
this change permits distinct label sets to be composed together, now that the label set encoder is not consumed. a new implementation for tuples `(A, B)` is provided.
this commit includes a test case showing that a metric family can compose two label sets together, and that such a family can successfully be digested by the python client library.
`derive-encode` is altered to generate code matching this new trait signature, and has been bumped to version 0.5.0 as a result of this breaking change in the `prometheus-client` library.

feat(encoding)!: `EncodeLabelSet::encode()` uses reference

---

CHANGELOG.md
src/metrics/family.rs

fixes #231.
this introduces a new method to `Family<S, M, C>` to help alleviate the risk of deadlocks when accessing multiple series within a given metrics family.
this returns a plain `M`, rather than the `MappedRwLockReadGuard<M>` RAII guard returned by `get_or_create()`.
a test case is introduced in this commit to demonstrate that structures accessing multiple series within a single expression will not accidentally create a deadlock.

feat(metrics/family): 🍫 add `Family::get_or_create_owned()`

---

examples/io_write.rs

Help users learn how to directly write data to an object implementing `std::io::Write`.
Doing some tests with 1,000 counters:
* Directly to a String: 454KB of RAM
* Directly to a file: 305KB of RAM
Closes out #258

Add example using std::io::Write

---

derive-encode/Cargo.toml
derive-encode/src/lib.rs
derive-encode/tests/build/redefine-prelude-symbols.rs
derive-encode/tests/lib.rs

This PR expands prelude symbols like `Ok()` and `prometheus_client` to absolute paths to make it more hygienic.
1. Add new dev-dependency [`trybuild`](https://docs.rs/trybuild/latest/trybuild/) to test procedure macro.
2. Expand the following symbols to absolute paths
1. `prometheus_client::encoding::*` -> `::prometheus_client::encoding::*`
2. `std::result::Result` -> `::core::result::Result`
3. `std::fmt::Error` -> `::core::fmt::Error`
4. `Ok(())` -> `::core::result::Result::Ok(())`
5. `std::fmt::Write` -> `::core::fmt::Write`
According to [proc-macro-workshop]:
> Generally all macros (procedural as well as macro_rules) designed to be used
> by other people should refer to every single thing in their expanded code
> through an absolute path, such as std::result::Result. …

fix(derive-encode): expand prelude symbols to absolute paths

---

CHANGELOG.md
src/encoding.rs

There was a bug in the `impl EncodeGaugeValue for u64` implementation due to the `as i64` cast.
The implementation only checked if `self == u64::MAX`, this is wrong since `u64::MAX` is not the only value that cannot be represented by an `i64`.
The range of values is actually `self > i64::MAX`. `u64::MAX == 2^64 - 1` whereas `i64::MAX == 2^63 - 1`, this means there are `2^63` `u64` values that are not representable by an `i64`, not just `i64::MAX`. Delegating the checks to `i64::try_from(self)` ensures the logic is right. For this reason I also switched the rest of the implementations to use `N::from` instead of `as N` since the `N::from` function is only implemented for types whose conversion is infallible, this guarantees no such issues will ever happen.
The only `as` cast left is `u64 …

refactor(encoding): remove `as` casts
